mailServer:
  host: ${MAIL_SERVER_HOST}
  port: ${MAIL_SERVER_PORT}
  email: ${MAIL_SERVER_EMAIL}
  password: ${MAIL_SERVER_PASSWORD}
  protocol: ${MAIL_SERVER_PROTOCOL}
  isSSL: ${MAIL_SERVER_IS_SSL}

frontend:
  base-endpoint: ${FRONTEND_BASE_ENDPOINT}

backend:
  base-endpoint: ${BACKEND_BASE_ENDPOINT}